version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=usertest
      - MONGO_PASSWORD=passtest

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usertest
      - MONGO_INITDB_ROOT_PASSWORD=passtest
