version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=usertest
      - MONGO_PASSWORD=passtest
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usertest
      - MONGO_INITDB_ROOT_PASSWORD=passtest
    volumes:
      - mongo-db:/data/db
