version: "3"
services:
  node-app:
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
